### ISSUE TITLE
Test all queries from testing-library

### ISSUE THREAD

**Issue by calebeby** [cloudfour/test-mule#6]
- [x] `findBy*`
- [x] `getBy*`
- [x] `queryBy*`
- [x] `findAllBy*`
- [x] `getAllBy*`
- [x] `queryAllBy*`

---

- [x] `*ByLabelText`
- [x] `*ByPlaceholderText`
- [x] `*ByText`
- [x] `*ByAltText`
- [x] `*ByTitle`
- [x] `*ByDisplayValue`
- [x] `*ByRole`
- [x] `*ByTestId`

---

- I think these should be in the `tests` folder rather than the `examples` folder. I think we should try to only have more realistic, complete, useful tests in `examples`.
- For queries that fail, we should use `test.skip(` when we make PR's so that we can avoid making the full test suite fail.
- Our test suite should also make sure that the queries fail successfully when they are supposed to fail, using `.toThrow`

**Comment by emersonthis** [comment]
Looks like the ✅ s refer to the ones that are working. Not the tests that have been written. Correct? My gut is to write dedicated tests for all (even the ones that appear in working examples). Make sense?

**Comment by calebeby** [comment]
I wrote the tests yesterday but I forgot to push them. They are pushed now: https://github.com/cloudfour/test-mule/tree/main/tests/testing-library-queries
